### ISSUE TITLE
[newrelic-k8s-metrics-adapter] Review the docs for values that could have changed

### ISSUE THREAD

**Issue by kang-makes** [newrelic/newrelic-k8s-metrics-adapter#39]
- [x] Take a look if this work should be fone with `helm-docs` or `frigate`.
- [x] Review that the values.yaml is properly documented to enable the creation of the README.md file automatically.
- [x] Review docs.newrelic.com for any `values.yaml` that should be changed in the integrations/kubernetes integration.

**Comment by alvarocabanas** [comment]
Docs PR https://github.com/newrelic/docs-website/pull/6623

**Comment by alvarocabanas** [comment]
https://github.com/newrelic/docs-website/pull/6623
