### ISSUE TITLE
Add support to queries with a "SELECT attribute OR 0" clause

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-k8s-metrics-adapter#55]
Right now the NRQL query for the metrics adapter doesn't allow queries in this format:

`FROM JMSMetricEvents SELECT average(stepQueueLength) OR 0 WHERE name='StepQueueLength'

That is because the API returns 2 results since it detects to elements on the select clause and we return an error.

The reason why a user would like to have this behaviour is a scenario like the following:

- I hava a metric there for 24 hours that makes my pods to be scaled to 10 
- The metric disappears because it has not been emitted in the time that it takes to disappear.
- For some reason, they want the pods to be scaled to min -for example 1- if the metric is not there.
- Then with the actual solution they can't do it, because it would not scale anything up or down.

**Comment by gsanchezgavier** [comment]
By design queries must return just 1 value. 

I'm changing this to a Feature request kind of issue.
