### ISSUE TITLE
histogrampercentile metrics are not parsing corectly

### ISSUE THREAD

**Issue by anoopwebs** [newrelic/newrelic-k8s-metrics-adapter#71]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Trying to add a new externalMetrics with histogrampercentile metrics and throwing `Error: failed parsing key`

[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

HELM chart - https://artifacthub.io/packages/helm/newrelic/nri-bundle
Version - 4.7.3

Use the above helm chart with externalMetrics values like below
I use terraform helm provider with set block to set values 

```
set {
        name  = "newrelic-k8s-metrics-adapter.config.externalMetrics.http_95percentile_response_ms_15min.query"
        value = "FROM Metric SELECT histogrampercentile(http_request_buckets_milliseconds_bucket, 95) SINCE 15 MINUTES AGO"
    }
```

## Expected Behavior

External metrics should be added to `/apis/external.metrics.k8s.io/v1beta1/`
`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/"`

## Relevant Logs / Console output

```
│ Error: failed parsing key "newrelic-k8s-metrics-adapter.config.externalMetrics.http_95percentile_response_ms_15min.query" with value FROM Metric SELECT histogrampercentile(http_request_buckets_milliseconds_bucket, 95) SINCE 15 MINUTES AGO, key " 95) SINCE 15 MINUTES AGO" has no value
│
│   with module.nri_bundle[0].helm_release.newrelic_bundle,
│   on ../../../../modules/cluster-tools/newrelic-bundle/main.tf line 9, in resource "helm_release" "newrelic_bundle":
│    9: resource "helm_release" "newrelic_bundle" {
```

## Your Environment

OS - MacOs Monterey 12.0.1

Terraform and Provider versions 
```
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.16.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
``` 

## Additional context
The same query works fine in NR Query builder

<img width="1685" alt="Screen Shot 2022-07-18 at 4 14 20 PM" src="https://user-images.githubusercontent.com/1245226/179609683-fd6a0cd5-fef9-4847-bfa3-1546b05cb315.png">

**Comment by marcsanmi** [comment]
Hi,

I would like to confirm a couple of things for us to have the full context.

Could you share the `values.yaml`? Or the config map in case you can't provide the values.

This error is a Terraform error?
> │ Error: failed parsing key "newrelic-k8s-metrics-adapter.config.externalMetrics.http_95percentile_response_ms_15min.query" with value FROM Metric SELECT histogrampercentile(http_request_buckets_milliseconds_bucket, 95) SINCE 15 MINUTES AGO, key " 95) SINCE 15 MINUTES AGO" has no value
│
│   with module.nri_bundle[0].helm_release.newrelic_bundle,
│   on ../../../../modules/cluster-tools/newrelic-bundle/main.tf line 9, in resource "helm_release" "newrelic_bundle":
│    9: resource "helm_release" "newrelic_bundle" {

**Comment by anoopwebs** [comment]
@marcsanmi Thanks for taking a look, here you asked
1. Please find the configMap, 
```
{
    "apiVersion": "v1",
    "data": {
        "config.yaml": "accountID: 2429158\ncacheTTLSeconds: 30\nexternalMetrics:\n  average_transaction_duration_15min:\n    query: FROM Transaction SELECT average(duration) SINCE 15 minutes AGO\n  total_transaction_count_5min:\n    query: SELECT count(*) FROM Transaction SINCE 5 minutes AGO\n  total_transaction_error_count_5min:\n    query: FROM TransactionError SELECT count(*) SINCE 5 minutes AGO\n"
    },
    "kind": "ConfigMap",
    "metadata": {
        "annotations": {
            "meta.helm.sh/release-name": "newrelic-bundle",
            "meta.helm.sh/release-namespace": "newrelic"
        },
        "creationTimestamp": "2022-06-09T13:01:21Z",
        "labels": {
            "app.kubernetes.io/instance": "newrelic-bundle",
            "app.kubernetes.io/managed-by": "Helm",
            "app.kubernetes.io/name": "newrelic-k8s-metrics-adapter",
            "app.kubernetes.io/version": "0.2.0",
            "helm.sh/chart": "newrelic-k8s-metrics-adapter-0.7.5"
        },
        "name": "newrelic-bundle-newrelic-k8s-metrics-adapter",
        "namespace": "newrelic",
        "resourceVersion": "119364358",
        "uid": "be410fa0-c171-48e9-9453-f5f1e0d5e665"
    }
}
```
2. `This error is a Terraform error?` Yes, running the helm chart using terraform helm provider and this is error from terraform.

**Comment by carlossscastro** [comment]
Hi @anoopwebs 

Thanks for your reply and additional information. Would you mind visiting [New Relic Support](https://support.newrelic.com/), and open a support ticket depending on your support level. The support team will help prioritize this issue.

Please provide a link to this GitHub issue when submitting your support ticket.

Thanks!

**Comment by carlossscastro** [comment]
I'm closing this issue for the moment and we will follow up on the support ticket.
