### ISSUE TITLE
1.0.0 released Helm chart has 0.2.0 image tag

### ISSUE THREAD

**Issue by depohmel** [newrelic/newrelic-k8s-metrics-adapter#84]
When newrelic-k8s-metrics-adapter is rendered as standalone chart main deployment uses `0.2.0` image tag instead of released one (`1.0.0` for example)

How Repo: 

Download tar file from github releases. https://github.com/newrelic/newrelic-k8s-metrics-adapter/releases/tag/newrelic-k8s-metrics-adapter-1.0.0
Untar. 
run ```helm template test ./newrelic-k8s-metrics-adapter  --set personalAPIKey=foo --set config.accountID=111 --set cluster=cluster| grep "newrelic/newrelic-k8s-metrics-adapter:"```

you will see the following
```
image: "newrelic/newrelic-k8s-metrics-adapter:0.2.0"
```

^^ Provide a general summary of the issue in the title above. ^^ 

## Description
Describe the problem you're encountering.
TIP: Do NOT share sensitive information, whether personal, proprietary, or otherwise! 

## Expected Behavior
I expect to see released tag :) 
```
image: "newrelic/newrelic-k8s-metrics-adapter:1.0.0"
```

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. 

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by sigilioso** [comment]
Hi @depohmel ,

Thanks for contributing by submitting the issue.

`1.0.0` is the [latests chart version](https://github.com/newrelic/newrelic-k8s-metrics-adapter/blob/33e81f629fbeb8d1d6512ac71d39779c93a625b1/charts/newrelic-k8s-metrics-adapter/Chart.yaml#L4). It uses the latests application version (in other words, the latests Docker image version) which is `0.0.2`. It can be a bit confusing because both the chart and the application realeases are in the Github releases section.

I hope this helps clarifying.

**Comment by depohmel** [comment]
Hello @sigilioso, thanks for the info. 

I see so you are using the same repo and releases for helm chart and actual code.... not the bets practice, but as long as it works. 

1 more thing this is form official NR helm repo:
```
 helm search repo newrelic
NAME                                 	CHART VERSION	APP VERSION	DESCRIPTION
newrelic/newrelic-infra-operator     	0.6.1        	0.6.0      	Moved to https://github.com/newrelic/newrelic-i...
newrelic/newrelic-infrastructure     	2.10.1       	2.11.0     	Moved to https://github.com/newrelic/nri-kubern...
newrelic/newrelic-k8s-metrics-adapter	0.3.3        	0.2.0      	Moved to https://github.com/newrelic/newrelic-k...
```
